.github/workflows/ci.yml
The following CI job would have caught the error in #3, and can hopefully prevent such errors in the future
=> Add address sanitizer to CI

.github/workflows/ci.yml, Cargo.toml, build.rs, gen/src/lib.rs, src/bin/gribber/cli.rs, src/bin/gribber/commands/decode.rs, src/bin/gribber/commands/inspect.rs, src/bin/gribber/commands/list.rs, src/codetables/old.rs, src/context.rs, src/datatypes/sections.rs, src/decoders/complex.rs, src/decoders/jpeg2000/ext.rs, src/decoders/jpeg2000/mod.rs, src/decoders/run_length.rs, src/decoders/simple.rs, src/reader.rs, src/utils.rs
This PR consists mostly of fixes for clippy lints to make the code a bit more rusty.
Two other larger changes are in the `GribInt` trait and postfix on `CliError` to comply with the clippy lints.
This PR also fixes a bug with potentially [unused IO](https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount) which could cause issues in the future.
=> Fix Clippy lints and add to CI

README.md
Add crates.io and deps.rs shields to README for easier access to those websites from the repo.
Deps.rs badge also informs about security of dependencies used in the crate, which can be really helpful for users. Currently, it shows `insecure` ([as for many other crates](https://github.com/chronotope/chrono/issues/602)) due to issues with chrono but I believe it is useful in long term to have such badge in README.
=> Add crates.io and deps.rs shields to README

Cargo.toml
As noted in comments in PR #6, openjpeg-sys 1.0.2 also triggered a build failure on `windows-latest`.
So, this PR limits openjpeg-sys to 1.0.3 for now as a workaround.
Closes #16.
=> Fix build failures with openjpeg-sys 1.0.4

src/bin/gribber/commands/info.rs, src/context.rs, tests/cli/commands/decode.rs, tests/cli/commands/info.rs, tests/cli/commands/inspect.rs, tests/cli/commands/list.rs, tests/cli/utils/testdata.rs
This PR adds multi-message data support for CLI.
Regarding support for multi-message data, this is not a complete end, as there are still some usability and data accessibility issues in the library crate.
Part of #13.
=> CLI: add support for multi-message data

.github/workflows/pages.yml
This PR will allow development version documentation to be built on GitHub Actions and deployed to GitHub Pages.
It would be nice to have the latest (development) version of the documentation automatically built and available on GitHub Pages. It will also motivate me to enhance the documentation.
=> Documentation deployment to GitHub Pages

cli/src/bin/gribber/commands/decode.rs, cli/src/bin/gribber/commands/inspect.rs, cli/src/bin/gribber/commands/list.rs, examples/decode_surface.rs, src/context.rs, src/decoders/common.rs, src/decoders/simple.rs
This PR introduces `SubMessage::decode()` and removes `Grib2::get_values()`.
Until now, it was necessary to use `Grib2::get_values()` to call a decoding function on data. However, it does not work well with other APIs, especially the submessage iterators that are being enhanced recently.
Submessage iterators make it easy to discover and filter submessages. However, decoding found submessages is inefficient because users need to pass the indices of the found submessages to `Grib2::get_values()` one by one.
This PR adds a `decode()` method to the submessage itself, allowing users to directly decode the submessages identified using the iterator.
=> Introduce SubMessage::decode() and remove Grib2::get_values()

cli/src/commands/decode.rs, examples/decode_surface.rs, src/context.rs, src/decoders/common.rs, src/decoders/complex.rs, src/decoders/jpeg2000/mod.rs, src/decoders/run_length.rs, src/decoders/simple.rs, src/utils.rs
This PR introduces `Grib2SubmessageDecoder`, which replaces `SubMessage::decode()`, to return an iterator instead of a boxed slice when decoding.
Until now, a boxed slice was returned when decoding. However, in many cases, users loop over the return values. Also, they often want to use a vector as a data structure to store that collection of values.
Now, by returning an iterator in decoding, users can loop directly over values or store the collection of values in a data structure of their choice.
A slight speedup is also achieved. Until now, while using iterators in the decoding process, the results of decoding were temporarily stored in a vector and passed to subsequent processing or finally stored in a boxed slice. This time, we were able to eliminate such unnecessary storage (although …
=> Return an iterator instead of a boxed slice when decoding

Cargo.toml, cli/Cargo.toml, cli/src/commands/info.rs, src/datatypes/sections.rs, src/error.rs
This PR provides migration to Chrono v0.4.23.
In Chrono v0.4.23, `Utc::ymd()` and `Date::and_hms()`, which cause panics for invalid inputs, are deprecated in favor of APIs returning `LocalResult`. Also, `Utc::with_ymd_and_hms()` is newly introduced.
This PR makes an API change; `Identification::ref_time()` now returns `chrono::DateTime` wrapped by `Result`.
=> Chrono v0.4.23 migration

cli/tests/cli/commands/decode.rs, cli/tests/cli/utils/testdata.rs, src/decoders/common.rs, src/decoders/complex.rs, src/decoders/jpeg2000/mod.rs, src/decoders/simple.rs
This PR fixes #32 by adding support for "nbit =0" cases to the complex packing decoder (and JPEG 2000 code stream format decoder), which was added to the simple packing decoder in response to #15.
=> Add support for cases where nbit is 0 in complex packing and JPEG 2000 code stream format

cli/tests/cli/commands/decode.rs, cli/tests/cli/utils/testdata.rs, src/utils.rs
This PR is a follow-up to #33 to fix a panic with 'attempt to multiply with overflow' in decoding complex packing data.
The panic was caused by reading a 3-byte parameter starting with `0x80` as a positive value instead of a negative value. For example, `0x80_cc_cc` was read as `52428` instead of `-52428`.
Closes #34.
=> Fix a panic with 'attempt to multiply with overflow' in decoding complex packing data

src/context.rs, src/datatypes/sections.rs, src/error.rs, src/grid.rs, src/lib.rs
This PR adds support for computation of latitudes and longitudes of grid points in the library. Among the various grids available in GRIB, this PR adds support for the latitude/longitude grid (Template 3.0), which I believe is the most commonly used.
With the addition of initial support for Section 3, initial support for all sections is now complete.
=> Add support for computation of latitudes and longitudes of grid points (for the lat/lon grid (Template 3.0))

cli/src/commands/decode.rs, cli/tests/cli/commands/decode.rs, src/grid.rs
This PR makes the "decode" subcommand print grid points' lat/lon values as well as data using a feature introduced at #39. In addition, improvements are made to the appearance of the text output.
=> CLI: make the "decode" subcommand print grid points' lat/lon values as well as data

src/reader.rs
This PR fixes an issue that wrong offset values are stored in reading a message starting from a non-zero position.
Since incorrect offset values are stored, re-reading and decoding submessages using those offset values may lead to incorrect value output, crashes, etc.
Closes #38.
=> Fix an issue that wrong offset values are stored in reading a message starting from a non-zero position

src/context.rs, src/datatypes/sections.rs, src/grid.rs, src/lib.rs
As a follow-up to #39 and #41, this PR makes grid-related types and methods publicly accessible, and also provide some documentation and examples for them.
=> Make grid-related types and methods publicly accessible

cli/src/cli.rs, cli/src/commands/decode.rs, cli/src/commands/info.rs, cli/src/commands/inspect.rs, cli/src/commands/list.rs, examples/decode_surface.rs, examples/find_surfaces.rs, src/cookbook.rs, src/decoders/common.rs, src/lib.rs, src/parser.rs, src/reader.rs
This PR moves all types except code tables directly under the crate root, without type name changes.
This makes incompatible changes to the API.
Due to my own unfamiliarity in the early stages of development, the library crate exposed the internal module hierarchy to the outside world as is.
However, this makes it difficult to refactor with internal hierarchical structure changes.
From the user's point of view, it is also difficult to grasp the full picture of what types exist in the API documentation.
This change solves these problems and will help future refactoring.
As for the code tables, I continue to keep the modules separate, as I plan to add various types (which should be machine-generated in the future), and putting them in the same level as the other types for data processing …
=> Move all types except code tables directly under the crate root

README.md, examples/find_surfaces.rs
This PR adds example code in README.md to show the usage of the API.
Since grib-rs is a library crate, it would be better if possible users could see in the README what the coding experience is like.
=> Include example code in README.md to show the usage of the API

README.md, cli/src/commands/list.rs, examples/decode_layer.rs, examples/find_layers.rs, examples/list_layers.rs, src/cookbook.rs
This PR replaces the word "surfaces" with "layers" to describe submessages.
The word "surface" has been used in README.md and elsewhere as a plain term to describe the concept of a submessage, but this is not appropriate, since a single submessage can have multiple surfaces.
=> Replace the word "surfaces" with "layers" for submessages

src/cookbook.rs
This PR includes GRIB tools from ecCodes in the comparison of GRIB processors in the cookbook.
=> Include GRIB tools from ecCodes in the comparison of GRIB processors in the cookbook

build.rs
This PR improves an error message from `cargo build` to suggest `git submodule update --init`.
Current:
Caused by:
process didn't exit successfully: `/path/to/grib-rs/target/.../build-script-build` (exit status: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:10:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
After improvement:
Caused by:
process didn't exit successfully: `/path/to/grib-rs/target/.../build-script-build` (exit status: 1)
--- stderr
Error: "def/CCT is empty; run `git submodule update --init`"
A senior member of the company I am working for asked me when he had an error trying to build grib-rs.
I could instantly imagine that …
=> Suggest `git submodule update --init` in build failure

cli/tests/cli/commands/decode.rs, cli/tests/cli/utils/testdata.rs, src/decoders/complex.rs, src/utils.rs
This PR adds support for Code Table 5.5 (missing value management for complex packing).
The logic for decoding complex packing when nbit is 0 was incorrect and wrong values were output.
The reason was that I wrote the process based on an incorrect understanding.
This time I read the source code of wgrib2, understood it again, and rewrote the process.
This is the 4th step of NDFD GRIB data support discussed in #59.
=> NDFD GRIB data support part 4: correctly handle cases where nbit is 0 in the complex packing decoder

src/context.rs, src/datatypes/sections.rs, src/grid.rs
This PR splits a grid point index iterator from the latitude/longitude iterator to prepare for Lambert grid support.
Also, this PR adds a new method `SubMessage::ij()` to allow users to use grid point indices.
=> NDFD GRIB data support part 6: split a grid point index iterator from the latitude/longitude iterator

Cargo.toml, src/grid.rs, src/grid/earth.rs
This PR adds support for Code Table 3.2 (shape of the reference system).
That support is required in implementation of Lambert conformal support.
=> NDFD GRIB data support part 7: add support for Code Table 3.2 (shape of the reference system)

.github/workflows/ci.yml, Cargo.toml, cli/Cargo.toml, src/datatypes/sections.rs, src/error.rs, src/grid.rs
This PR adds support for Template 3.30 (Lambert conformal) using `proj` crate.
As part of Template 3.30 support, this PR introduces a feature named `gridpoints-proj`.
This feature has two roles:
- first, to allow users to choose to do their own geographic calculations;
- second, to make it easier to build this crate, even for targets that have difficulty building `proj` crate that wraps PROJ written in C++.
=> NDFD GRIB data support part 8: add support for Template 3.30 (Lambert conformal)

.github/workflows/pages.yml, Cargo.toml, README.md, web/Cargo.toml, web/index.html, web/src/drop_area.rs, web/src/main.rs
This PR makes an example GRIB2 viewer web app available on GitHub Pages.
It will be available on https://noritada.github.io/grib-rs/viewer/.
The web app still only has the ability to list submessages in GRIB2.
The ability to display grid point values within submessages will be available in the near future.
=> Example GRIB2 viewer web app

src/context.rs, src/datatypes/sections.rs, src/grid/lambert.rs, src/grid/latlon.rs, src/grid/polar_stereographic.rs
This PR adds functionality to access the grid shape without iteration.
The shape of the grid is included in the parameters of the grid definition and is therefore accessible to the user if he/she makes the effort, but currently that access is not as easy as it could be.
This feature may be useful when plotting grid point values on canvas, since it allows the distribution of grid points to be known before the actual decoding of the grid point values.
=> Add functionality to access the grid shape without iteration

web/Cargo.toml, web/index.html, web/src/drop_area.rs, web/src/main.rs, web/src/palette.rs, web/src/submessage_modal.rs, web/src/utils.rs
This PR adds functionality to the web app to display grid point values in a GRIB2 submessage.
At this time, there are several issues with this display feature:
- Color map selection support
- Display of color map legend and unit
- Proper support for scanning modes
- Fix for an issue that noise sometimes appears in the display
- Improvements of UX when there is a wait for display
- Error messages for submessages whose Section 3 and/or Section 5 is supported
These issues will be addressed in due course.
=> Web app: add functionality to display grid point values in a GRIB2 submessage

src/datatypes/sections.rs
This PR makes the lib crate return an error for quasi-regular latitude/longitude grids.
Quasi-regular latitude/longitude grids should be supported but are not yet supported.
=> Strictly return an error for quasi-regular latitude/longitude grids

cli/src/commands/list.rs, cli/tests/cli/commands/list.rs, demo/index.html, demo/src/main.rs, src/datatypes/sections.rs, src/grid/lambert.rs, src/grid/latlon.rs, src/grid/polar_stereographic.rs
This PR adds a feature to return the short name defined for the grid.
Short names are based on ecCodes `gridType` strings, such as `"regular_ll"` and `"lambert"`.
This PR also changes CLI and demo web app to show that grid type string in the submessage list view.
=> Add a feature to return the short name defined for the grid, based on ecCodes `gridType` strings

src/decoder/complex.rs, src/decoder/jpeg2000.rs, src/decoder/param.rs, src/decoder/png.rs, src/decoder/simple.rs
This PR provides strict checking of type of original field values in complex packing.
Current implementation assumes that original field values are floating-point.
Almost all decoders check the value type, but the check was missing in the complex packing decoders.
=> Strict checking of type of original field values in complex packing

src/decoder.rs, src/decoder/jpeg2000.rs, src/decoder/param.rs, src/decoder/png.rs, src/decoder/simple.rs
This PR makes decoders correctly handle cases where nbit is 0.
Following two possible issues will be corrected by this PR:
- Simple packing and JPEG 2000 code stream format decoders have returned $R$ for all points when nbit was 0,
although they should return $R * 10^{-D}$.
I noticed this problem when I was reading the source code of wgrib2.
Although I have went through every one of data files I had on hand,
I have not encountered any data files where the problem actually occurs,
since every message has had $D$ value of 0 when nbit is 0.
- PNG format decoder may possibly have crashed when nbit was 0.
I have not encountered any data files where the problem actually occurs,
since I only have PNG-format encoded data files whose nbit is 16.
=> Fix decoders handling cases where nbit is 0

src/codetables.rs, src/codetables/external.rs, src/codetables/old.rs, src/context.rs, src/datatypes/product_attributes.rs
This PR provides new `Parameter` struct and some NCEP codes defined as enum variants.
This PR allows users to obtain a `Parameter` struct from a submessage.
This struct provides functions concerning parameters (weather elements and other physical quantities),
such as parameter matching using NCEP codes and text representation.
NCEP codes are implemented as enum variants so that users can take full advantage of Rust's static typing,
e.g., with the assistance of IDE for NCEP code typing.
This PR provides only a limited number of NCEP codes.
Most of the remaining NCEP codes will be provided in subsequent PRs.
=> Submessage filtering improvement part 1:  `Parameter` struct and NCEP code mock-ups

src/codetables/external.rs, src/context.rs, src/datatypes/product_attributes.rs
This PR provides a more user-friendly API to check the identity of numerical parameters and named codes.
With this API, users are now able to check the identity like this:
```rust
param.is_identical_to(NCEP::HGT)
```
So, submessage filtering can be done like this:
```rust
grib2.iter().find(|submessage| {
submessage.parameter().is_some_and(|param| param.is_identical_to(NCEP::HGT))
});
```
=> Submessage filtering improvement part 2: more user-friendly API to check the identity of numerical parameters and named codes

codegen/src/lib.rs, codegen/tests/01-normal-case.rs, codegen/tests/02-not-empty-enum.stderr
This PR makes minor improvements to the proc macro.
Now the proc macro copies attributes from the source enum.
=> Submessage filtering improvement part 4: make minor improvements to the proc macro for code generation

src/grid/latlon.rs
This PR fixes longitude computation failures due to inconsistent grid definitions.
Lat/lon computation of grid points failed for `testdata/CMC_glb_TMP_ISBL_1_latlon.24x.24_2021051800_P000.grib2`.
The root cause of the failure is an inconsistency between the longitude range and scanning mode in the grid definition;
although longitudes are expected to increase since the scanning mode is `0b01000000`,
the starting longitude is 180.00 degrees and the ending longitude is 179.76 degrees.
This PR corrects the issue by putting in a process that allows computation across the prime meridian.
Closes #51.
=> Fix longitude computation failures due to inconsistent grid definitions

codegen/src/lib.rs, codegen/src/param_codes.rs, codegen/tests/01-normal-case.rs, codegen/tests/data/table
This PR makes 2 specification changes for grib-codegen to support ECMWF codes:
- change of the code normalization rule
- change of the way to conversion from numbers to enum variants
First, since only 3 NCEP codes begin with a number, and those numbers are single digits,
I originally used a code normalization rule such as replacing "4" with "Four".
However, since ECMWF codes seem to include numeric-only codes such as `260120`,
in this PR, I change the normalization rule to add an underscore prefix to the code.
Second, since it is unnecessarily complicated to remap from a number to a number and then
convert the number to an enum variant,
in this PR, I change it so that we can derive the enum variant directly from the number.
=> Submessage filtering improvement part 5: make specification changes to support ECMWF codes

.github/workflows/ci.yml
This PR fixes build failure on Linux in CI.
The build failure occurs when the lib crate has a dependency on the proj-sys crate.
The error is like this:
```
error: failed to run custom build command for `proj-sys v0.23.2`
Caused by:
process didn't exit successfully: `/home/runner/work/grib-rs/grib-rs/target/debug/build/proj-sys-a8ac46c1b648abb4/build-script-build` (exit status: 101)
--- stdout
(snip)
--- stderr
pkg-config unable to find existing libproj installation: 
pkg-config exited with status code 1
> PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags proj proj >= 9.2.0
The system library `proj` required by crate `proj-sys` was not found.
The file `proj.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its …
```
=> Fix build failure of the proj-sys crate on Linux

build.rs
Fixes a `clippy::uninlined-format-args` detected in `build.rs`
=> fix format string in build.rs

Cargo.toml
This MR updates proj to 0.30.
The project I'm working on that uses `grib-rs` already enables `proj/bundled_proj`.  I would also like to take advantage of the fact that the newest `proj-sys` uses `libsqlite3-sys` which provides a similar `bundled` feature.
All tests passed when I ran `cargo test --workspace`.
I ran `cargo +nightly clippy --workspace` per the contribution guide.  The version I'm using, `clippy 0.1.88 (25cdf1f674 2025-04-28)`, identifies unrelated code issues that I mentioned over on #115.
=> update proj to 0.30

src/context.rs
This PR extends `from_slice()` to take an owned sequence of bytes as an argument.
Now the function is renamed to `from_bytes()`.
=> Extend `from_slice()` to take an owned sequence of bytes as an argument

cli/Cargo.toml, cli/src/cli.rs, cli/src/commands/decode.rs, cli/src/commands/info.rs, cli/src/commands/inspect.rs, cli/src/commands/list.rs, cli/tests/cli/commands/decode.rs
This PR adds support for standard input/output to CLI.
Previously, `gribber` could only handle file names as input/output targets and could not read/write data via pipes.
Now that standard input/output can be handled, data can be exchanged with external commands through pipes.
The following example reads an xz-compressed GRIB2 file and creates an xz-compressed decoded result without creating a temporary file:
xzcat testdata/gdas.t00z.sfluxgrbf000.grib2.0.xz | gribber decode - 0.0 -b - | xz > decoded.xz
Note: #117 was an API improvement in preparation for this PR.
=> CLI: standard input/output support

.github/workflows/ci.yml, .gitignore, .zed/settings.template.json, Cargo.toml, cli/Cargo.toml, cli/src/commands/info.rs, src/codetables/grib2.rs, src/context.rs, src/datatypes/sections.rs, src/lib.rs, src/time.rs
This PR provides following enhancements concerning time-related information APIs.
Dependency on chrono crate is changed from "always dependent" to "dependent only when chrono feature is enabled".
Raw values of the reference time read from the data are now returned as `grib::UtcDateTime`, and the functionality to return values interpreted as `chrono::DateTime` should be available only when `chrono` feature is enabled.
- It would be better to have as few dependent crates in the crate core as possible .
- If the data has an invalid reference time set such as "2025-13-32 25:61", an error is currently returned as a reference time.
This is because the reading of the value and its conversion (interpretation) to `chrono::DateTime` are included in one process.
It is better to separate the read …
=> Time-related information API enhancements

Cargo.toml
This PR fixes a build failure with older versions of chrono.
The error message is like this:
```
error[E0432]: unresolved import `chrono::TimeDelta`
--> src/time.rs:4:37
|
4 | use chrono::{DateTime, LocalResult, TimeDelta, TimeZone, Utc};
|                                     ^^^^^^^^^ no `TimeDelta` in the root
```
In the above case, we used chrono v0.4.23 for the build.
The cause is an error in specifying the dependent version.
`chrono::TimeDelta` has been available since v0.4.34.
Prior to that, it was named `chrono::Duration`.
=> Correct the dependency on chrono

src/decoder.rs
This PR changes test data used in doc tests for `Grib2SubmessageDecoder`.
The original test data used JPEG 2000 code stream format to store grid point values, which may require enabling a specific feature for decoding in the future.
=> Change test data used in doc tests for `Grib2SubmessageDecoder`

Cargo.toml, README.md, build.rs, build/doc.rs, build/main.rs, src/lib.rs
This PR provides crate-level documentation.
Until now, no doc comments were written at the crate level, and the top page of the documentation contained only automatically generated API information.
=> Crate-level documentation

README.md, cli/src/commands.rs, cli/src/commands/dump.rs, cli/tests/cli/commands/common.rs
This PR adds a CLI subcommand "dump" to dump the content of a GRIB submessage.
This is also part of "True Template Support" (#140).
=> True Template Support: add a CLI subcommand "dump" to dump the content of a GRIB submessage
